from __future__ import annotations


def workspace_document() -> str:
    """Return the dependency-free local Capital Cockpit shell."""

    return r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Clausula · Capital Cockpit</title>
<style>
:root{color-scheme:light dark;--bg:#f4f5f2;--surface:rgba(255,255,255,.86);--strong:#fff;--soft:#eceee9;--ink:#171a17;--muted:#687068;--line:rgba(26,34,27,.12);--accent:#315b49;--good:#2d6a4f;--warn:#8a5a17;--bad:#9f3a38;--shadow:0 18px 50px rgba(40,48,41,.08);--radius:18px}
@media(prefers-color-scheme:dark){:root{--bg:#111411;--surface:rgba(26,30,26,.9);--strong:#1c211d;--soft:#222823;--ink:#eef1ed;--muted:#a1aaa1;--line:rgba(235,242,235,.11);--accent:#8db8a2;--good:#83c5a4;--warn:#dfb36e;--bad:#e78e8a;--shadow:0 22px 60px rgba(0,0,0,.26)}}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 16% -10%,color-mix(in srgb,var(--accent) 10%,transparent),transparent 34rem),var(--bg);color:var(--ink);font:14px/1.45 Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;letter-spacing:-.006em}button,input{font:inherit}button{color:inherit}.shell{max-width:1480px;margin:0 auto;padding:26px 30px 56px}.topbar,.hero,.panel-head,.context,.list{display:flex;justify-content:space-between;gap:16px}.topbar{align-items:center;margin-bottom:30px}.brand{display:flex;align-items:center;gap:11px;font-weight:760;letter-spacing:-.035em;font-size:18px}.mark{width:28px;height:28px;border:1px solid var(--line);border-radius:9px;display:grid;place-items:center;background:var(--strong);box-shadow:var(--shadow)}.mark:before{content:"C";font:700 17px Georgia,serif;color:var(--accent)}.actions{display:flex;align-items:center;gap:8px}.pill,.icon{border:1px solid var(--line);background:var(--surface);backdrop-filter:blur(10px)}.pill{border-radius:999px;padding:7px 10px;font-size:11px;font-weight:720;color:var(--muted);letter-spacing:.06em}.icon{width:36px;height:36px;border-radius:11px;cursor:pointer}.hero{align-items:end;margin-bottom:22px}.hero>div:first-child{max-width:760px}h1{margin:0;font-size:clamp(34px,4vw,58px);line-height:.98;letter-spacing:-.065em;font-weight:770}.hero p{margin:12px 0 0;color:var(--muted);font-size:15px}.flow{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:6px;max-width:470px}.flow span{padding:6px 9px;border-radius:999px;background:var(--soft);color:var(--muted);font-size:11px;font-weight:650}.flow b{color:var(--accent)}
.controls{display:grid;grid-template-columns:minmax(260px,1.5fr) minmax(160px,.7fr) minmax(160px,.7fr) auto;gap:10px;padding:12px;background:var(--surface);border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow);margin-bottom:14px}.field label{display:block;font-size:10px;text-transform:uppercase;letter-spacing:.1em;font-weight:750;color:var(--muted);margin:0 0 5px 3px}.field input{width:100%;height:42px;border:1px solid var(--line);border-radius:11px;padding:0 12px;background:var(--strong);color:var(--ink);outline:none}.field input:focus{border-color:var(--accent);box-shadow:0 0 0 3px color-mix(in srgb,var(--accent) 10%,transparent)}.primary{align-self:end;height:42px;border:0;border-radius:11px;padding:0 18px;background:var(--accent);color:white;font-weight:740;cursor:pointer}.primary:disabled{opacity:.55;cursor:wait}.context{min-height:28px;align-items:center;color:var(--muted);font-size:12px;margin:0 4px 10px}.state{display:inline-flex;align-items:center;gap:7px}.dot{width:7px;height:7px;border-radius:99px;background:var(--muted)}.dot.good{background:var(--good);box-shadow:0 0 0 4px color-mix(in srgb,var(--good) 12%,transparent)}.dot.bad{background:var(--bad);box-shadow:0 0 0 4px color-mix(in srgb,var(--bad) 12%,transparent)}
.error{display:none;margin-bottom:12px;border:1px solid color-mix(in srgb,var(--bad) 35%,var(--line));background:color-mix(in srgb,var(--bad) 8%,var(--surface));color:var(--bad);padding:11px 13px;border-radius:12px;font-size:12px}.error.show{display:block}.kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:12px}.card,.panel{background:var(--surface);border:1px solid var(--line);box-shadow:var(--shadow);backdrop-filter:blur(14px)}.card{border-radius:16px;padding:17px 18px;min-height:118px}.eyebrow{color:var(--muted);text-transform:uppercase;letter-spacing:.1em;font-size:10px;font-weight:760}.metric{font-size:27px;letter-spacing:-.045em;font-weight:750;margin-top:16px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.metric.small{font-size:21px}.sub{margin-top:4px;color:var(--muted);font-size:11px}.private .sensitive{color:transparent!important;text-shadow:0 0 8px var(--ink);user-select:none}
.grid{display:grid;grid-template-columns:minmax(0,1.65fr) minmax(330px,.8fr);gap:12px;align-items:start}.stack{display:grid;gap:12px}.panel{border-radius:var(--radius);padding:19px;overflow:hidden}.panel-head{align-items:flex-start;margin-bottom:16px}.panel h2{margin:0;font-size:16px;letter-spacing:-.025em}.caption{color:var(--muted);font-size:11px;margin-top:3px}.badge{border-radius:999px;padding:5px 8px;font-size:10px;font-weight:760;letter-spacing:.04em;background:var(--soft);color:var(--muted);white-space:nowrap}.badge.good{color:var(--good);background:color-mix(in srgb,var(--good) 12%,transparent)}.badge.warn{color:var(--warn);background:color-mix(in srgb,var(--warn) 13%,transparent)}.badge.bad{color:var(--bad);background:color-mix(in srgb,var(--bad) 12%,transparent)}
.alloc{display:grid;grid-template-columns:140px minmax(0,1fr) 88px;gap:12px;align-items:center;padding:7px 0}.alloc-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-weight:610}.bar{height:7px;border-radius:99px;background:var(--soft);overflow:hidden}.bar span{display:block;height:100%;border-radius:99px;background:var(--accent);min-width:2px}.right{text-align:right;font-variant-numeric:tabular-nums;color:var(--muted)}.rule{display:grid;grid-template-columns:10px minmax(0,1fr) auto;gap:10px;align-items:start;padding:11px 0;border-top:1px solid var(--line)}.rule-dot{width:8px;height:8px;border-radius:99px;margin-top:5px;background:var(--muted)}.rule-dot.compliant{background:var(--good)}.rule-dot.violation{background:var(--bad)}.rule-dot.unavailable{background:var(--warn)}.title{font-weight:650}.copy{color:var(--muted);font-size:11px;margin-top:3px}.rail{position:relative;padding:0 0 17px 19px;border-left:1px solid var(--line);margin-left:4px}.rail:before{content:"";position:absolute;left:-4px;top:5px;width:7px;height:7px;border-radius:99px;background:var(--accent);box-shadow:0 0 0 4px var(--strong)}.list{align-items:flex-start;padding:10px 0;border-top:1px solid var(--line)}.list:first-child,.rule:first-child{border-top:0;padding-top:0}.main{min-width:0}.main .title{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.empty{color:var(--muted);padding:20px 0 8px;text-align:center;font-size:12px}.gap{display:grid;grid-template-columns:78px 1fr;gap:10px;padding:9px 0;border-top:1px solid var(--line)}.gap:first-child{border-top:0;padding-top:0}.gap-kind{font-size:10px;font-weight:760;text-transform:uppercase;color:var(--warn)}footer{color:var(--muted);font-size:10px;margin-top:18px;padding:0 4px;display:flex;justify-content:space-between;gap:20px}
@media(max-width:980px){.shell{padding:20px 16px 42px}.hero{display:block}.flow{justify-content:flex-start;margin-top:18px}.controls{grid-template-columns:1fr 1fr}.field:first-child{grid-column:1/-1}.kpis{grid-template-columns:1fr 1fr}.grid{grid-template-columns:1fr}}@media(max-width:590px){.pill{display:none}.controls{grid-template-columns:1fr}.field:first-child{grid-column:auto}.primary{width:100%}.kpis{grid-template-columns:1fr}.alloc{grid-template-columns:95px minmax(0,1fr) 70px}footer{display:block}}
</style>
</head>
<body>
<div class="shell">
<header class="topbar"><div class="brand"><span class="mark"></span>Clausula</div><div class="actions"><span class="pill">LOCAL · READ ONLY</span><button class="icon" id="privacy" aria-label="Toggle privacy" title="Mask monetary values">◉</button></div></header>
<section class="hero"><div><h1>Capital Cockpit</h1><p>A decision-first view of capital state, policy boundaries, feasible plans and the memory of what you actually decided.</p></div><div class="flow"><span><b>State</b></span><span>Boundary</span><span>Attention</span><span>Evidence</span><span>Plan</span><span>Decision</span><span>Review</span></div></section>
<section class="controls"><div class="field"><label for="portfolio">Portfolio UUID</label><input id="portfolio" autocomplete="off" placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"></div><div class="field"><label for="asof">As of</label><input id="asof" type="date"></div><div class="field"><label for="known">Known as of</label><input id="known" type="date"></div><button class="primary" id="load">Load snapshot</button></section>
<div class="error" id="error"></div><div class="context"><span class="state"><span class="dot" id="state-dot"></span><span id="context">Enter a portfolio and load a point-in-time snapshot.</span></span><span id="stamp"></span></div>
<section class="kpis"><div class="card"><div class="eyebrow">Capital</div><div class="metric sensitive" id="capital">—</div><div class="sub" id="capital-sub">Canonical portfolio valuation</div></div><div class="card"><div class="eyebrow">Cash</div><div class="metric sensitive" id="cash">—</div><div class="sub sensitive" id="cash-sub">Liquidity inside this portfolio</div></div><div class="card"><div class="eyebrow">Largest position</div><div class="metric small" id="largest">—</div><div class="sub sensitive" id="largest-sub">Concentration</div></div><div class="card"><div class="eyebrow">Data freshness</div><div class="metric small" id="freshness">—</div><div class="sub" id="freshness-sub">Oldest accepted position price</div></div></section>
<main class="grid"><div class="stack"><section class="panel"><div class="panel-head"><div><h2>Capital state</h2><div class="caption">Allocation is descriptive; policy determines whether it is acceptable.</div></div><span class="badge" id="complete-badge">Not loaded</span></div><div id="allocation"><div class="empty">Load a snapshot to inspect allocation.</div></div></section><section class="panel"><div class="panel-head"><div><h2>Policy boundary</h2><div class="caption">Effective and knowledge-dated constraints evaluated against the same valuation.</div></div><span class="badge" id="policy-badge">—</span></div><div id="policies"><div class="empty">No policy evaluation loaded.</div></div></section><section class="panel"><div class="panel-head"><div><h2>Data gaps</h2><div class="caption">Clausula fails closed instead of inventing missing market truth.</div></div><span class="badge" id="gap-badge">—</span></div><div id="gaps"><div class="empty">No snapshot loaded.</div></div></section></div><aside class="stack"><section class="panel"><div class="panel-head"><div><h2>Decision memory</h2><div class="caption">What you chose remains separate from what later happened.</div></div><span class="badge" id="decision-badge">—</span></div><div id="decisions"><div class="empty">No decisions loaded.</div></div></section><section class="panel"><div class="panel-head"><div><h2>Plans</h2><div class="caption">Persisted deterministic scenarios, not live brokerage intent.</div></div><span class="badge" id="plan-badge">—</span></div><div id="plans"><div class="empty">No plans loaded.</div></div></section></aside></main>
<footer><span>Canonical facts remain in the local ledger. This workspace is a projection.</span><span>0.x · no autonomous brokerage execution</span></footer>
</div>
<script>
(()=>{"use strict";const $=id=>document.getElementById(id);const mk=(cls,text)=>{const n=document.createElement("div");if(cls)n.className=cls;if(text!==undefined&&text!==null)n.textContent=String(text);return n};const clear=n=>{while(n.firstChild)n.removeChild(n.firstChild)};const iso=v=>v&&v.length===10?v+"T23:59:59+00:00":v;const short=v=>v?String(v).slice(0,10):"—";const tone=s=>s==="compliant"||s==="complete"||s==="funded"?"good":s==="violation"||s==="incomplete"||s==="shortfall"?"bad":"warn";
function setBadge(id,text,t){const n=$(id);n.className="badge"+(t?" "+t:"");n.textContent=text}function badge(text,t){const n=document.createElement("span");n.className="badge"+(t?" "+t:"");n.textContent=text;return n}function money(v,c){if(v===null||v===undefined||v==="")return"—";const n=Number(v);if(!Number.isFinite(n))return String(v);try{return new Intl.NumberFormat(undefined,{style:"currency",currency:c||"USD",maximumFractionDigits:2}).format(n)}catch(_){return n.toLocaleString()+" "+(c||"")}}function pct(v){const n=Number(v);return Number.isFinite(n)?(n*100).toFixed(Math.abs(n)>=.1?1:2)+"%":"—"}function headroomLabel(row,c){if(!row||row.headroom==null)return"—";return row.unit==="base_currency"?money(row.headroom,c):pct(row.headroom)}function error(msg){const n=$("error");n.textContent=msg;n.classList.add("show")}function noError(){const n=$("error");n.textContent="";n.classList.remove("show")}
async function snapshot(payload){const r=await fetch("/workspace/snapshot",{method:"POST",cache:"no-store",headers:{"Accept":"application/json","Content-Type":"application/json"},body:JSON.stringify(payload)});const b=await r.json();if(!r.ok)throw new Error(b.message||b.error||String(r.status));return b}
function allocation(v){const root=$("allocation");clear(root);const rows=(v.allocation||[]).slice().sort((a,b)=>Number(b.base_value)-Number(a.base_value));if(!rows.length){root.appendChild(mk("empty","No valued allocation lines."));return}rows.forEach(x=>{const row=mk("alloc");row.appendChild(mk("alloc-name",x.asset_type));const bar=mk("bar"),fill=document.createElement("span");fill.style.width=Math.max(0,Math.min(100,Number(x.weight||0)*100))+"%";bar.appendChild(fill);row.appendChild(bar);const val=mk("right sensitive",pct(x.weight));val.title=money(x.base_value,v.base_currency);row.appendChild(val);root.appendChild(row)})}
function gaps(v){const root=$("gaps");clear(root);const rows=v.gaps||[];setBadge("gap-badge",rows.length?rows.length+" unresolved":"No gaps",rows.length?"warn":"good");if(!rows.length){root.appendChild(mk("empty","Valuation has no unresolved data gaps."));return}rows.slice(0,12).forEach(x=>{const row=mk("gap");row.appendChild(mk("gap-kind",x.kind||"gap"));row.appendChild(mk("copy",[x.message,x.instrument_id,x.currency].filter(Boolean).join(" · ")));root.appendChild(row)})}
function policies(items,headroom,currency){const root=$("policies");clear(root);if(!items.length){setBadge("policy-badge","No policy","");root.appendChild(mk("empty","No policy is attached to this portfolio."));return}const overall=items.some(x=>x.status==="violation")?"violation":items.some(x=>x.status==="unavailable")?"unavailable":"compliant";const tight=(headroom||[]).find(x=>x.headroom!=null);setBadge("policy-badge",tight?overall+" · "+headroomLabel(tight,currency)+" room":overall,tone(overall));if(tight){const pressure=mk("list"),main=mk("main");main.appendChild(mk("title","Tightest boundary · "+tight.rule_key));main.appendChild(mk("copy",[tight.policy_name,tight.rule_type,"signed headroom "+headroomLabel(tight,currency)].filter(Boolean).join(" · ")));pressure.appendChild(main);pressure.appendChild(badge(tight.status,tone(tight.status)));root.appendChild(pressure)}items.forEach(ev=>{const head=mk("list"),main=mk("main");main.appendChild(mk("title",ev.policy_name||ev.policy_id));main.appendChild(mk("copy",ev.version_number?"Policy v"+ev.version_number+" · "+(ev.results||[]).length+" rules":ev.reason||"Unavailable at cutoff"));head.appendChild(main);head.appendChild(badge(ev.status,tone(ev.status)));root.appendChild(head);(ev.results||[]).filter(r=>r.status!=="compliant").slice(0,8).forEach(r=>{const row=mk("rule");row.appendChild(mk("rule-dot "+r.status));const copy=mk("");copy.appendChild(mk("title",r.rule_key));const bounds=[r.lower_bound!=null?"min "+r.lower_bound:null,r.upper_bound!=null?"max "+r.upper_bound:null].filter(Boolean).join(" · ");copy.appendChild(mk("copy",[r.rule_type,r.current_value!=null?"current "+r.current_value:"unavailable",bounds].filter(Boolean).join(" · ")));row.appendChild(copy);row.appendChild(badge(r.severity||r.status,tone(r.status)));root.appendChild(row)})})}
function decisions(items){const root=$("decisions");clear(root);const rows=(items||[]).slice().sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).slice(0,8);setBadge("decision-badge",String((items||[]).length),"");if(!rows.length){root.appendChild(mk("empty","No decision memory for this portfolio yet."));return}rows.forEach(x=>{const row=mk("rail");row.appendChild(mk("title",x.title||x.intent||"Decision"));row.appendChild(mk("copy",[x.intent,short(x.as_of),x.plan_id?"planned":null].filter(Boolean).join(" · ")));root.appendChild(row)})}
function plans(items){const root=$("plans");clear(root);const rows=(items||[]).slice().sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).slice(0,6);setBadge("plan-badge",String((items||[]).length),"");if(!rows.length){root.appendChild(mk("empty","No persisted plans for this portfolio."));return}rows.forEach(x=>{const row=mk("list"),main=mk("main");main.appendChild(mk("title",x.name||"Plan"));main.appendChild(mk("copy",[short(x.as_of),x.policy_version_id?"policy-bound":null].filter(Boolean).join(" · ")));row.appendChild(main);root.appendChild(row)})}
function valuation(v,meta,envelope){const c=v.base_currency||meta.base_currency||"USD";$("capital").textContent=money(v.complete?v.total_value:v.partial_value,c);$("capital-sub").textContent=v.complete?"Complete canonical valuation":"Partial value · unresolved inputs excluded";const cash=(v.allocation||[]).find(x=>x.asset_type==="cash");$("cash").textContent=money(cash?cash.base_value:"0",c);if(envelope&&envelope.status==="funded"){$("cash-sub").textContent="Deployable "+money(envelope.deployable_cash,c)+" · reserve "+money(envelope.required_reserve,c)}else if(envelope&&envelope.status==="shortfall"){$("cash-sub").textContent="Reserve shortfall "+money(envelope.reserve_gap,c)+" · required "+money(envelope.required_reserve,c)}else if(envelope&&envelope.status==="unconstrained"){$("cash-sub").textContent=(cash?pct(cash.weight)+" · ":"")+"no reserve policy"}else{$("cash-sub").textContent="Reserve capacity unavailable"}const big=(v.concentration||[])[0];$("largest").textContent=big?big.identifier:"—";$("largest-sub").textContent=big?pct(big.weight)+" · "+money(big.base_value,c):"No valued position";const dates=(v.positions||[]).map(x=>x.price_observed_at).filter(Boolean).sort();$("freshness").textContent=dates.length?short(dates[0]):"—";$("freshness-sub").textContent=dates.length?"Oldest accepted position price · "+dates.length+" lines":"No position price observations";setBadge("complete-badge",v.complete?"Complete":"Incomplete",v.complete?"good":"bad");$("state-dot").className="dot "+(v.complete?"good":"bad");allocation(v);gaps(v)}
async function load(){noError();const portfolio=$("portfolio").value.trim(),asof=iso($("asof").value),known=iso($("known").value||$("asof").value);if(!portfolio||!asof){error("Portfolio UUID and as-of date are required.");return}const btn=$("load");btn.disabled=true;btn.textContent="Loading…";try{const data=await snapshot({portfolio_id:portfolio,as_of:asof,known_as_of:known});valuation(data.valuation,data.portfolio,data.capital_envelope);policies(data.policies||[],data.risk_headroom||[],data.portfolio.base_currency);plans(data.plans||[]);decisions(data.decisions||[]);$("context").textContent=data.portfolio.name+" · "+data.portfolio.base_currency+" · as of "+short(data.as_of)+" · known "+short(data.known_as_of);$("stamp").textContent="Single local snapshot";try{localStorage.setItem("clausula.cockpit.portfolio",portfolio)}catch(_){}}catch(e){$("state-dot").className="dot bad";$("context").textContent="Snapshot unavailable";error(e instanceof Error?e.message:String(e))}finally{btn.disabled=false;btn.textContent="Load snapshot"}}
$("load").addEventListener("click",load);$("privacy").addEventListener("click",()=>{document.body.classList.toggle("private");$("privacy").textContent=document.body.classList.contains("private")?"○":"◉"});[$("portfolio"),$("asof"),$("known")].forEach(n=>n.addEventListener("keydown",e=>{if(e.key==="Enter")load()}));const today=new Date().toISOString().slice(0,10);$("asof").value=today;$("known").value=today;try{const saved=localStorage.getItem("clausula.cockpit.portfolio");if(saved)$("portfolio").value=saved}catch(_){}})();
</script>
</body></html>'''
